<?php

namespace TaskPlanerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findByUser(User $user)
    {
        return $this
            ->getEntityManager()
            ->createQuery(
                'SELECT t FROM TaskPlanerBundle:Task t JOIN TaskPlanerBundle:Category c WHERE c.user = :user'
            )
            ->setParameter('user', $user)
            ->getResult();
    }
}
